### ISSUE TITLE
Cannot install metasploit-framework

### ISSUE THREAD

**Issue by onskulis** [darkoperator/MSF-Installer#46]
Having an issue:

guru@antikvariatas:/opt/metasploit-framework$ sudo gem install metasploit_data_models -v '0.23.1'
Successfully installed metasploit_data_models-0.23.1
Parsing documentation for metasploit_data_models-0.23.1
Done installing documentation for metasploit_data_models after 2 seconds
1 gem installed
guru@antikvariatas:/opt/metasploit-framework$ sudo bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all
non-root users on this machine.
Gem::InstallError: metasploit_data_models requires Ruby version >= 2.1.
An error occurred while installing metasploit_data_models (0.23.1), and Bundler cannot continue.
Make sure that `gem install metasploit_data_models -v '0.23.1'` succeeds before bundling.
guru@antikvariatas:/opt/metasploit-framework$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [i686-linux]

Whats is wrong here?

**Comment by darkoperator** [comment]
Are you sure you do not have a version of ruby installed with APT and are only using Rbenv or RVM? al why open and issue here? I nuked the script so it would not work for quite a while now while a bug in framework is worked out so I doubt this is the script.

**Comment by darkoperator** [comment]
Just in case not complaining :) just curious if someone is sending people here since a lot of people have been posting about the same thing in the project issues.

**Comment by onskulis** [comment]
I had installed version of ruby via APT and I tried everything out.
Somehow it came to success with a command 'rvmsudo bundle install', I have no idea why.
And one more thing I had 2 different version of ruby in different folders. Like in /opt/metasploit-framework it was 2.1.5 and in /home/guru it was 2.2.0.... root always had 1.8 version. 

Im totally lost.

**Comment by darkoperator** [comment]
if you do rvm list how many versions of ruby does it show?

**Comment by onskulis** [comment]
On my old computer version were:
1.8
1.9 
2.1
as a normal user

and 
1.9 only as a root.



I installed fresh version of Kubuntu now. I almost get things work but I can run msfconsole only from /opt/metasploit-framework path.
If I try to run from my home directory I get following error:

`/usr/share/rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'metasploit-framework' (>= 0) among 94 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/ksno/.rvm/gems/ruby-2.2.0:/home/ksno/.rvm/gems/ruby-2.2.0@global:/opt/metasploit-framework/', execute `gem env` for more information
        from /usr/share/rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
        from /usr/share/rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
        from /home/ksno/.rvm/gems/ruby-2.2.0/bin/msfupdate:22:in `<main>'
        from /home/ksno/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/ksno/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
`


and if i run gem env I get:

`RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.6
  - RUBY VERSION: 2.2.0 (2014-12-25 patchlevel 0) [i686-linux]
  - INSTALLATION DIRECTORY: /home/ksno/.rvm/gems/ruby-2.2.0
  - RUBY EXECUTABLE: /usr/share/rvm/rubies/ruby-2.2.0/bin/ruby
  - EXECUTABLE DIRECTORY: /home/ksno/.rvm/gems/ruby-2.2.0/bin
  - SPEC CACHE DIRECTORY: /home/ksno/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/share/rvm/rubies/ruby-2.2.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-linux
  - GEM PATHS:
     - /home/ksno/.rvm/gems/ruby-2.2.0
     - /home/ksno/.rvm/gems/ruby-2.2.0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/ksno/.rvm/gems/ruby-2.2.0/bin
     - /home/ksno/.rvm/gems/ruby-2.2.0@global/bin
     - /usr/share/rvm/rubies/ruby-2.2.0/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /usr/share/rvm/bin`

**Comment by UbuntuKali** [comment]
darkoperator! There is a "Create a virtual hackbox" guide floating around out there with your name on it. It has the command down below to be ran. When running it just tells me it's a fatal error due to repository not being available. FYI!

# Install git first.
Apt-get install git
# Grab the script from Github.
Git clone https://github.com/darkoperator/MSF-Installer.git
# Move to the directory and list contents.
cd /MSF-Installer;ls
# Run the installer
./msf_install.sh -i -p -r
 
-i == Install Metasploit
-p == password to use for database (-p pass will set the password to pass, -p alone will generate a random pass)
-r == Install necessary Ruby Gems through RVM.

**Comment by darkoperator** [comment]
They need to update their guide :) the installer script has been dead for while since there is little effort from the Metasploit Team at Rapid7 on fixing the symlink bug properly.
